#!/usr/bin/env python3
"""Generate the minimised *reading view* of the library.

The reading view answers one question — *what does this code compute?* — by
deleting everything that answers a different one. Prose, typing and defensive
scaffolding are all valuable in the source tree and all noise when you are
tracing a derivation against a textbook on a phone.

Rewriting is done with :mod:`ast`, never with regular expressions: a regex that
matches ``: NDArray[np.float64]`` also matches the colon in a dict literal, and
a regex that matches a docstring also matches a string constant that happens to
sit first in a list. Parsing removes that whole class of mistake. Unparsing has
a useful side effect too — :func:`ast.unparse` regenerates source from the tree,
so inline comments are dropped for free and need no rule of their own.

=========================  =========================
Stripped                   Preserved
=========================  =========================
Docstrings, at every level ``import`` statements
Inline comments            Function and class signatures
Type annotations           Vector broadcasting and maths
Validation guard blocks    ``return`` expressions
=========================  =========================

A *validation guard block* is an ``if`` with no ``else`` branch whose body
ends in a ``raise`` and holds nothing before it but the assignments that build
the message — the shape that
``docs/conventions/style.md`` §8 requires validation to take. Isolating guards
from the maths is what makes them mechanically removable, which is why the
style rule and this tool are written against each other.

The output is a reading aid and is **not** importable: a dataclass stripped of
its annotations is no longer a dataclass. ``radar_forge_reading/`` is git-ignored
for that reason, and regenerated on demand.

Usage
-----
    uv run python tools/generate_reading_view.py
    uv run python tools/generate_reading_view.py --src src/radar_forge --out build/reading
"""

from __future__ import annotations

import argparse
import ast
import html
import shutil
import sys
from pathlib import Path, PurePosixPath

from pygments import highlight
from pygments.formatters import HtmlFormatter
from pygments.lexers import PythonLexer

__all__ = [
    "ReadingViewTransformer",
    "generate",
    "main",
    "minimise_source",
    "render_index",
    "render_module",
]

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SRC = REPO_ROOT / "src" / "radar_forge"
DEFAULT_OUT = REPO_ROOT / "radar_forge_reading"

_HEADER = "# Reading view — generated by tools/generate_reading_view.py. Do not edit.\n"


def _is_docstring(node: ast.stmt) -> bool:
    """Return True if ``node`` is a bare string expression, i.e. a docstring."""
    return (
        isinstance(node, ast.Expr)
        and isinstance(node.value, ast.Constant)
        and isinstance(node.value.value, str)
    )


def _is_guard(node: ast.stmt) -> bool:
    """Return True if ``node`` is a validation guard: ``if ...: raise ...``.

    The body must end in a ``raise`` and contain nothing before it but the
    assignments that build the message — the exact shape
    ``docs/conventions/style.md`` §8 prescribes::

        if range_m <= 0.0:
            msg = "range_m must be strictly positive."
            raise ValueError(msg)

    There must be no ``else`` branch, so an ``if`` that raises in one arm and
    computes in the other is never mistaken for a guard.
    """
    if not isinstance(node, ast.If) or node.orelse or not node.body:
        return False
    *prefix, last = node.body
    return isinstance(last, ast.Raise) and all(
        isinstance(stmt, ast.Assign | ast.AnnAssign) for stmt in prefix
    )


class ReadingViewTransformer(ast.NodeTransformer):
    """Strip prose, typing and guard clauses from a parsed module.

    The transformer is shape-preserving: signatures, imports, assignments,
    control flow and returns all survive, so the arithmetic a reader came for
    is exactly what is left.
    """

    def _clean_body(self, body: list[ast.stmt]) -> list[ast.stmt]:
        """Drop the docstring and the guard blocks from one suite.

        An emptied suite gets a ``pass`` so the result still parses.
        """
        kept: list[ast.stmt] = []
        for index, node in enumerate(body):
            if index == 0 and _is_docstring(node):
                continue
            if _is_guard(node):
                continue
            visited = self.visit(node)
            if visited is None:
                continue
            if isinstance(visited, list):
                kept.extend(visited)
            else:
                kept.append(visited)
        return kept or [ast.Pass()]

    def visit_Module(self, node: ast.Module) -> ast.Module:
        """Strip the module docstring and recurse into the module body."""
        node.body = self._clean_body(node.body)
        return node

    def visit_ClassDef(self, node: ast.ClassDef) -> ast.ClassDef:
        """Strip the class docstring and recurse into the class body."""
        node.body = self._clean_body(node.body)
        return node

    def visit_FunctionDef(self, node: ast.FunctionDef) -> ast.FunctionDef:
        """Strip the docstring, the annotations and the guards of a function."""
        _strip_arguments(node.args)
        node.returns = None
        node.body = self._clean_body(node.body)
        return node

    def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> ast.AsyncFunctionDef:
        """Strip the docstring, the annotations and the guards of a coroutine."""
        _strip_arguments(node.args)
        node.returns = None
        node.body = self._clean_body(node.body)
        return node

    def visit_If(self, node: ast.If) -> ast.If:
        """Recurse into both arms of an ``if`` that is not itself a guard."""
        node.body = self._clean_body(node.body)
        if node.orelse:
            node.orelse = self._clean_body(node.orelse)
        return node

    def visit_For(self, node: ast.For) -> ast.For:
        """Recurse into a ``for`` suite."""
        node.body = self._clean_body(node.body)
        if node.orelse:
            node.orelse = self._clean_body(node.orelse)
        return node

    def visit_While(self, node: ast.While) -> ast.While:
        """Recurse into a ``while`` suite."""
        node.body = self._clean_body(node.body)
        if node.orelse:
            node.orelse = self._clean_body(node.orelse)
        return node

    def visit_With(self, node: ast.With) -> ast.With:
        """Recurse into a ``with`` suite."""
        node.body = self._clean_body(node.body)
        return node

    def visit_Try(self, node: ast.Try) -> ast.Try:
        """Recurse into every suite of a ``try`` statement."""
        node.body = self._clean_body(node.body)
        node.orelse = self._clean_body(node.orelse) if node.orelse else []
        node.finalbody = self._clean_body(node.finalbody) if node.finalbody else []
        for handler in node.handlers:
            handler.body = self._clean_body(handler.body)
        return node

    def visit_AnnAssign(self, node: ast.AnnAssign) -> ast.stmt:
        """Rewrite an annotated assignment as a plain one.

        ``x: float = 3.0`` becomes ``x = 3.0``. A declaration with no value —
        a dataclass field, typically — becomes ``x = ...``, which keeps the
        field name visible even though the reading view is not importable.
        """
        value = node.value if node.value is not None else ast.Constant(value=Ellipsis)
        return ast.Assign(targets=[node.target], value=value, lineno=node.lineno)


def _strip_arguments(args: ast.arguments) -> None:
    """Remove every annotation from one argument list, in place."""
    everything = [
        *args.posonlyargs,
        *args.args,
        *args.kwonlyargs,
        *([args.vararg] if args.vararg else []),
        *([args.kwarg] if args.kwarg else []),
    ]
    for arg in everything:
        arg.annotation = None


def minimise_source(source: str, filename: str = "<unknown>") -> str:
    """Return ``source`` with prose, typing and guard clauses removed.

    Parameters
    ----------
    source : str
        The complete text of one Python module.
    filename : str, optional
        Name used in a :class:`SyntaxError` if ``source`` does not parse.

    Returns
    -------
    str
        Valid Python: the same computation, minus the docstrings, the inline
        comments, the annotations and the validation guard blocks.
    """
    tree = ast.parse(source, filename=filename)
    minimised = ReadingViewTransformer().visit(tree)
    ast.fix_missing_locations(minimised)
    return ast.unparse(minimised) + "\n"


# One stylesheet for every page. Dark by default — the view is mostly read on a
# phone, often at night — with a light palette for readers who ask for one.
_STYLE = """<style>
  :root {
    color-scheme: dark light;
    --bg: #0d1117; --fg: #e6edf3; --muted: #8b949e; --link: #58a6ff; --code-bg: #161b22;
  }
  @media (prefers-color-scheme: light) {
    :root { --bg: #ffffff; --fg: #1f2328; --muted: #59636e; --link: #0969da; --code-bg: #f6f8fa; }
  }
  body {
    background: var(--bg); color: var(--fg);
    font-family: system-ui, sans-serif; margin: 2rem auto; max-width: 56rem; padding: 0 1rem;
  }
  a { color: var(--link); }
  li { margin: 0.25rem 0; }
  code, pre { background: var(--code-bg); font-family: ui-monospace, Menlo, Consolas, monospace; }
  code { padding: 0.1rem 0.3rem; }
  pre { padding: 1rem; overflow-x: auto; line-height: 1.45; border-radius: 6px; }
  .muted { color: var(--muted); }
  .highlight pre { background: var(--code-bg); }
</style>"""

# Syntax colours for module pages, matched to the dark and light palettes above.
# types-Pygments leaves get_style_defs unannotated, hence the targeted ignores.
_HIGHLIGHT_STYLE = (
    "<style>\n"
    + HtmlFormatter(style="github-dark").get_style_defs(".highlight")  # type: ignore[no-untyped-call]
    + "\n@media (prefers-color-scheme: light) {\n"
    + HtmlFormatter(style="default").get_style_defs(".highlight")  # type: ignore[no-untyped-call]
    + "\n}\n</style>"
)


def _page(title: str, body: str, extra_head: str = "") -> str:
    """Wrap ``body`` in the shared HTML skeleton and stylesheet."""
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
{_STYLE}
{extra_head}
</head>
<body>
{body}
</body>
</html>
"""


def render_module(relative_path: str, source: str) -> str:
    """Return an HTML page displaying one minimised module.

    Browsers download or show ``.py`` files as bare text, so each module also
    gets a page of its own that renders the code in place, coloured by
    Pygments.

    Parameters
    ----------
    relative_path : str
        Output-relative POSIX path of the module, e.g. ``core/signal.py``.
    source : str
        The minimised source to display.

    Returns
    -------
    str
        A single self-contained HTML page.
    """
    depth = relative_path.count("/")
    index_href = "../" * depth + "index.html"
    name = PurePosixPath(relative_path).name
    body = f"""<p><a href="{index_href}">&larr; index</a>
  <span class="muted">· <a href="{html.escape(name)}">raw</a></span></p>
<h1>{html.escape(relative_path)}</h1>
{highlight(source, PythonLexer(), HtmlFormatter())}"""
    return _page(f"{relative_path} · radar-forge reading view", body, _HIGHLIGHT_STYLE)


def render_index(relative_paths: list[str]) -> str:
    """Return a minimal HTML index linking every generated module page.

    Parameters
    ----------
    relative_paths : list of str
        Output-relative POSIX paths, one per generated module.

    Returns
    -------
    str
        A single self-contained HTML page. It is deliberately plain: this is
        the page GitHub Pages serves, and a reading aid should not need a
        build step of its own.
    """
    items = "\n".join(
        f'    <li><a href="{html.escape(path)}.html">{html.escape(path)}</a></li>'
        for path in sorted(relative_paths)
    )
    body = f"""<h1>radar-forge reading view</h1>
<p>
  Minimised sources generated from <code>src/radar_forge/</code> by
  <code>tools/generate_reading_view.py</code>: the maths, with the docstrings,
  comments, type annotations and validation guards removed. Not importable, and
  never committed.
</p>
<ul>
{items}
</ul>"""
    return _page("radar-forge reading view", body)


def generate(src: Path, out: Path) -> list[Path]:
    """Write the minimised mirror of ``src`` into ``out``.

    Any existing ``out`` tree is removed first, so a deleted module never
    lingers as a stale page.

    Parameters
    ----------
    src : pathlib.Path
        Package root to read, normally ``src/radar_forge``.
    out : pathlib.Path
        Directory to write, normally ``radar_forge_reading``.

    Returns
    -------
    list of pathlib.Path
        Every file written: each ``.py``, its ``.py.html`` page, and ``index.html``.
    """
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    written: list[Path] = []
    relative_paths: list[str] = []
    for source_path in sorted(src.rglob("*.py")):
        relative = source_path.relative_to(src)
        target = out / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        minimised = minimise_source(
            source_path.read_text(encoding="utf-8"), filename=str(source_path)
        )
        target.write_text(_HEADER + minimised, encoding="utf-8")
        page = target.with_name(target.name + ".html")
        page.write_text(render_module(relative.as_posix(), minimised), encoding="utf-8")
        written.extend([target, page])
        relative_paths.append(relative.as_posix())

    index = out / "index.html"
    index.write_text(render_index(relative_paths), encoding="utf-8")
    written.append(index)
    return written


def main(argv: list[str] | None = None) -> int:
    """Parse arguments, generate the reading view, report what was written."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else None)
    parser.add_argument("--src", type=Path, default=DEFAULT_SRC, help="package root to read")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="directory to write")
    args = parser.parse_args(argv)

    src: Path = args.src
    if not src.is_dir():
        print(f"error: {src} is not a directory", file=sys.stderr)
        return 1

    written = generate(src, args.out)
    print(f"wrote {len(written)} files to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
